-- MENU
localization = {}
localization.menu = {}
localization.menu.start = {}
localization.menu.start.en = "New Game"
localization.menu.start.bg = "Нова Игра"
localization.menu.continue = {}
localization.menu.continue.en = "Continue"
localization.menu.continue.bg = "Продължи"
localization.menu.survival = {}
localization.menu.survival.en = "Survival Mode"
localization.menu.survival.bg = "Безкрайна Игра"
localization.menu.scores = {}
localization.menu.scores.en = "Scores"
localization.menu.scores.bg = "Резултати"
localization.menu.controls = {}
localization.menu.controls.en = "Controls"
localization.menu.controls.bg = "Управление"
localization.menu.exit = {}
localization.menu.exit.en = "Exit"
localization.menu.exit.bg = "Изход"
localization.menu.menu = {}
localization.menu.menu.en = "Go to Menu"
localization.menu.menu.bg = "Меню"
localization.menu.level = {}
localization.menu.level.en = "Continue"
localization.menu.level.bg = "Продължи"
for i=1,LEVELS_AMOUNT do
  localization.menu[i] = {}
  localization.menu[i].en = i
  localization.menu[i].bg = i
end
localization.menu.switchLanguages = {}
localization.menu.switchLanguages.en = "Press           to change langauges"
localization.menu.switchLanguages.bg = "Натисни           за да смениш езика"
localization.menu.switchLanguagesPosition = {}
localization.menu.switchLanguagesPosition.en = 247
localization.menu.switchLanguagesPosition.bg = 268

-- CONTROLS
localization.controls = {}
localization.controls.move = {}
localization.controls.move.en = "Move the martenitsa with the arrows"
localization.controls.move.bg = "Движи мартеничката със стрелките"
localization.controls.gather = {}
localization.controls.gather.en = "Gather knots to get long enough to wrap it around the checkpoints"
localization.controls.gather.bg = "Събирай възелчетата за да станеш дълга и да се увеш около точките"
localization.controls.menu = {}
localization.controls.menu.en = "You can press M to go back to the menu"
localization.controls.menu.bg = "Натисни М, за да се върнеш в менюто"
localization.controls.reset = {}
localization.controls.reset.en = "Press R to reset the level when you are stuck"
localization.controls.reset.bg = "Натисни R за да започнеш нивото отначало"
localization.controls.pause = {}
localization.controls.pause.en = "To pause the level at any time press ESC"
localization.controls.pause.bg = "За да спреш нивото на пауза натисни ESC"

-- PAUSE
localization.pause = {}
localization.pause.title = {}
localization.pause.title.en = "PAUSE"
localization.pause.title.bg = "ПАУЗА"
localization.pause.continue = {}
localization.pause.continue.en = "Press                 again to continue"
localization.pause.continue.bg = "Натисни                 отново, за да продължиш"
localization.pause.continuePosition = {}
localization.pause.continuePosition.en = 583
localization.pause.continuePosition.bg = 562
localization.pause.menu = {}
localization.pause.menu.en = "If you want to go back to the menu press"
localization.pause.menu.bg = "Ако искаш да се върнеш на менюто, натисни"
localization.pause.menuPosition = {}
localization.pause.menuPosition.en = 800
localization.pause.menuPosition.bg = 820

-- TUTORIAL
localization.tutorial = {}
localization.tutorial.eat = {}
localization.tutorial.eat.en = "Eat the knots to grow longer."
localization.tutorial.eat.bg = "Хапвай възелчетата, за да растеш."
localization.tutorial.wrap = {}
localization.tutorial.wrap.en = "Wrap yourself around the checkoints to finish the level."
localization.tutorial.wrap.bg = "Увий се около точките, за да завършиш нивото."

-- SCORES
localization.scores = {}
localization.scores.level = {}
localization.scores.level.en = "Level"
localization.scores.level.bg = "Ниво"
localization.scores.high = {}
localization.scores.high.en = "High Scores"
localization.scores.high.bg = "Най-високи точки"
localization.scores.death = {}
localization.scores.death.en = "Death Count"
localization.scores.death.bg = "Брой неуспехи"
localization.scores.survival = {}
localization.scores.survival.en = "Survival"
localization.scores.survival.bg = "Безкрай"

-- INFO
localization.info = {}
localization.info.playing = {}
localization.info.playing.en = "Thank you for playing Martenitsa!"
localization.info.playing.bg = "Благодаря ви, че изиграхте Мартеница!"
localization.info.developed = {}
localization.info.developed.en = "Developed by Margarita Ganeva"
localization.info.developed.bg = "Изработена от Маргарита Ганева"
localization.info.music = {}
localization.info.music.en = "Music by Ravnec Folklore Band"
localization.info.music.bg = "С музика на Фолклорна формация Равнец"
localization.info.thanks = {}
localization.info.thanks.en = "Big thanks to"
localization.info.thanks.bg = "Благодарности на"
localization.info.names = {}
localization.info.names.en = "Veliko Dragiev\nBerend Krebs\nIvan Kasarov\nLyubomir Gizdov\nStefan Manolov\nAnna Velcheva\nDimitar Panov\nBogdan Kurtev\nKristina Stoyanova\nPeko Atanasov\nIva Popova\nRahul Anand\nJoshua Batchelor\nSuhail Ahmed\nAngus Thomsen\nKristina Stefanova\nStanislav Bozhkov\n"
localization.info.names.bg = "Велико Драгиев\nBerend Krebs\nИван Касъров\nЛюбомир Гиздов\nСтефан Манолов\nАнна Велчева\nДимитър Панов\nБогдан Куртев\nКристина Стоянова\nПеко Атанасовv\nИва Попова\nRahul Anand\nJoshua Batchelor\nSuhail Ahmed\nAngus Thomsen\nКристина Стефанова\nСтанислав Божков\n"
localization.info.support = {}
localization.info.support.en = "for the testing, advising and the overall support"
localization.info.support.bg = "за подкрепата, тестването и безценните съвети"
localization.info.graphics = {}
localization.info.graphics.en = "All graphics are drawn with"
localization.info.graphics.bg = "Всички картинки са рисувани с"
localization.info.levels = {}
localization.info.levels.en = "The levels are designed using"
localization.info.levels.bg = "Нивата са направени използвайки"
localization.info.written = {}
localization.info.written.en = "And the game is written in"
localization.info.written.bg = "И играта е написана на"
localization.info.with = {}
localization.info.with.en = "with"
localization.info.with.bg = "със"
localization.info.level1Title = {}
localization.info.level1Title.en = "Introduction"
localization.info.level1Title.bg = "Въведение"
localization.info.level1Text = {}
localization.info.level1Text.en = "A martenitsa is a red and white bracelet made of yarn that people in Bulgaria give to each other on March 1st as a wish for health and a long life. This is all part of the pagan tradition of Baba Marta, or Granny March, who represents the advent of spring.\n\nThe colors of the martenitsa symbolise many things. It is believed that the white wool represents the melting snow and the red twine represents the setting sun.\n\nAnother meaning behind the martenitsa's colors is that the white symbolises man and the red - woman, or that they represent purity and life or health and strength."
localization.info.level1Text.bg = ""
localization.info.level2Title = {}
localization.info.level2Title.en = "Baba Marta"
localization.info.level2Title.bg = "Баба Марта"
localization.info.level2Text = {}
localization.info.level2Text.en = "'Mart' is the bulgarian word for March and 'baba' - the word for grandma.\n\nIn old folklore 'Baba Marta' is portrayed as a volatile and moody woman. It is believed that when she is happy, skies are blue and the sun will shine, but when Baba Marta is disgruntled, she will bring rain and wind.\n\nAccording to the legends, Baba Marta only visits clean and tidy homes, so at the end of February people would clean their abode in preparation."
localization.info.level2Text.bg = ""
localization.info.level3Title = {}
localization.info.level3Title.en = "Traditions"
localization.info.level3Title.bg = "Традиции"
localization.info.level3Text = {}
localization.info.level3Text.en = "On March 1st, Bulgarians give martenitsi to their family, friends and neighbours. They may be in the form of a simple bracelet of entwined red and white wool or a brooch of red and white wool tassels.\n\nFront doors get decorated with enormous red and white pompoms or with woollen dolls called 'Pizho and Penda'. Pizho is the male doll and is usually crafted from white wool. Penda is the female, red doll and is distinguished by her skirt."
localization.info.level3Text.bg = ""
localization.info.level4Title = {}
localization.info.level4Title.en = "Traditions"
localization.info.level4Title.bg = "Традиции"
localization.info.level4Text = {}
localization.info.level4Text.en = "Martenitsi are worn until Baba Marta shows a sign that spring is truly here. This may be the first stork returning from the South, or the green buds on a fruit tree.\n\nOnce spring has revealed itself, the martenitsa is hung from the branches of a budding tree and people make a wish. This act is said to make the tree strong and healthy.\n\nSome people put their martenitsa under a stone and the creature that is closest to the stone on the next day would determine the person's health for the rest of the year. If the creature is a larva or a worm, the forthcoming year will be healthy and successful. The same luck is associated with an ant; however, the person will have to work hard to achieve success. If the creature near the stone is a spider, then the person is in trouble and will be lacking in luck, health, or personal success for the next twelve months."
localization.info.level4Text.bg = ""
localization.info.level5Title = {}
localization.info.level5Title.en = "Bulgarian legends"
localization.info.level5Title.bg = "Български легенди"
localization.info.level5Text = {}
localization.info.level5Text.en = "Among the legends about the colors of the martenitsa is the story of Khan Kubrat, the founder of Bulgaria, who was nearing the end of his life. He knew this and asked his sons to vow to keep the various Bulgar tribes together to defend the country. However, soon after Khan Kubrat's death, their land was invaded by the Khazars. They took over the capital and kidnapped Khan Kubrat's daughter, Houba.\n\nOf the five sons, one, Bayan, joined with the Khazars in an attempt to stay with his sister. The other brothers: Kotrag, Asparukh, Kuber and Alcek looked north and south for a land away from their enemies. They had agreed that if they found such a place they would send Bayan and Houba a bird with a piece of thread tied to its leg.\n\nEventually, the imprisoned siblings received the awaited message and tried to set off secretly, but the Khazars soon found out and followed them. Bayan and Houba didn't know the soldiers were so close and were about to set the bird on its return course, when Bayan was wounded by an arrow, fired by the Khazars. Dripping blood onto the white thread, Bayan still managed to release the bird, and he and his sister continued their journey to find their brothers. When the siblings finally met, Bayan was nearly dead. Asparukh welcomed the dying man, tore pieces of bloodstained white cloth into small strips and gave them to his soldiers in honour of the brave Bayan."
localization.info.level5Text.bg = ""
localization.info.level6Title = {}
localization.info.level6Title.en = "Bulgarian legends"
localization.info.level6Title.bg = "Български легенди"
localization.info.level6Text = {}
localization.info.level6Text.en = "According to another legend about Khan Asparukh, founder of the First Bulgarian Kingdom, the Bulgarians reached a land beyond the Danube and decided to settle there. Khan Asparukh was happy with his find and wanted the pagan god Tangra to bless the new kingdom, so he decided to offer him a gift. By tradition, a sacrificial fire had to be lit with a sprig of dry dill, but there was no dill around.\n\nWhile Asparukh was pondering how to please Tangra, a falcon perched on his shoulder. The bird had a sprig of dill tied to its leg with a white woollen thread, half tinged with red. The dill had been sent by Asparukh's sister Houba, who had dreamt of her brother's dilemma. During the long flight, the falcon's wing got sore and part of the thread was soaked in blood. Asparukh lit the sacrificial fire and attached the thread onto his clothing, so it would bring him good health."
localization.info.level6Text.bg = ""
localization.info.level7Title = {}
localization.info.level7Title.en = "Around the world"
localization.info.level7Title.bg = "Около света"
localization.info.level7Text = {}
localization.info.level7Text.en = "Bulgaria is not the only country in the world celebrating the advent of March and the coming of spring. Some countries even have traditions that include giving and wearing of martenitsas.\n\nRomania also commemorates the first day of March with a celebration known as martisor. Men offer women a jewel or some other adornment tied to a red and white string. It is traditionally worn for 12 days and it gives the wearer strength and good health for the coming year.\n\nMoldova's celebration is very similar to that of Romania, except that people give each other a gold or silver brooch on a red and white string, which they pin to their lapel.\n\nIn Greece, people braid bracelets called martis, made from red and white strings, and give them out to children on March 1st. Martis are worn until the midnight mass of the Greek Orthodox Easter. On this day, bonfires are lit and the bracelets are removed and thrown into the fires."
localization.info.level7Text.bg = ""
