sounds = {}
sounds.scissors = love.audio.newSource("asset/scissors.wav", "static")
sounds.scissors:setVolume(0.5)
sounds.waterHit = love.audio.newSource("asset/water-hit.wav", "static")
sounds.wallHit = love.audio.newSource("asset/wall-hit.wav", "static")
sounds.buttonPress = love.audio.newSource("asset/button-press.wav", "static")
sounds.buttonRelease = love.audio.newSource("asset/button-release.wav", "static")
sounds.doorOpen = love.audio.newSource("asset/rock-move.wav", "static")
sounds.knotEat1 = love.audio.newSource("asset/knot-eat.wav", "static")
sounds.knotEat2 = love.audio.newSource("asset/knot-eat2.wav", "static")
sounds.birds = love.audio.newSource("asset/birds.wav", "static")
sounds.birds:setLooping(true)
