sounds = {}
sounds.intro = love.audio.newSource("asset/intro.wav", "static")
sounds.victory = love.audio.newSource("asset/victory.wav", "static")
sounds.credits = love.audio.newSource("asset/credits.ogg", "static")
sounds.menuPress = love.audio.newSource("asset/menu-press.wav", "static")
sounds.menuMove = love.audio.newSource("asset/menu-move.wav", "static")
sounds.scissors = love.audio.newSource("asset/scissors.wav", "static")
sounds.waterHit = love.audio.newSource("asset/water-hit.wav", "static")
sounds.wallHit = love.audio.newSource("asset/wall-hit.wav", "static")
sounds.buttonPress = love.audio.newSource("asset/button-press.wav", "static")
sounds.buttonRelease = love.audio.newSource("asset/button-release.wav", "static")
sounds.doorOpen = love.audio.newSource("asset/rock-move.wav", "static")
sounds.doorClose = love.audio.newSource("asset/rock-init.wav", "static")
sounds.knotEat1 = love.audio.newSource("asset/knot-eat.wav", "static")
sounds.knotEat2 = love.audio.newSource("asset/knot-eat2.wav", "static")
sounds.walking = love.audio.newSource("asset/walking.wav", "static")
sounds.walking:setLooping(true)
sounds.turning = love.audio.newSource("asset/turning.wav", "static")
sounds.dying = love.audio.newSource("asset/dying.wav", "static")
sounds.birds = love.audio.newSource("asset/birds.wav", "static")
sounds.birds:setLooping(true)
