sprites = {}
sprites.button = love.graphics.newImage('sprites/button.png')
sprites.buttonActive = love.graphics.newImage('sprites/button_active.png')
sprites.buttonInactive = love.graphics.newImage('sprites/button_inactive.png')

sprites.checkpoint = love.graphics.newImage('sprites/checkpoint.png')
sprites.checkpointDone = love.graphics.newImage('sprites/checkpoint_done.png')

sprites.coin = love.graphics.newImage('sprites/coin.png')
sprites.controls = love.graphics.newImage('sprites/controls.png')
sprites.hitWall = love.graphics.newImage('sprites/hit_wall.png')
sprites.hitWater = love.graphics.newImage('sprites/hit_water.png')

sprites.doorRed = love.graphics.newImage('sprites/door_red.png')
sprites.doorBlue = love.graphics.newImage('sprites/door_blue.png')
sprites.doorGreen = love.graphics.newImage('sprites/door_green.png')
sprites.doorYellow = love.graphics.newImage('sprites/door_yellow.png')
sprites.doorWhite = love.graphics.newImage('sprites/door_white.png')
sprites.keyPressedRed = love.graphics.newImage('sprites/key_pressed_red.png')
sprites.keyReleasedRed = love.graphics.newImage('sprites/key_released_red.png')
sprites.keyPressedBlue = love.graphics.newImage('sprites/key_pressed_blue.png')
sprites.keyReleasedBlue = love.graphics.newImage('sprites/key_released_blue.png')
sprites.keyPressedGreen = love.graphics.newImage('sprites/key_pressed_green.png')
sprites.keyReleasedGreen = love.graphics.newImage('sprites/key_released_green.png')
sprites.keyPressedYellow = love.graphics.newImage('sprites/key_pressed_yellow.png')
sprites.keyReleasedYellow = love.graphics.newImage('sprites/key_released_yellow.png')
sprites.keyPressedWhite = love.graphics.newImage('sprites/key_pressed_white.png')
sprites.keyReleasedWhite = love.graphics.newImage('sprites/key_released_white.png')

sprites.knot = love.graphics.newImage('sprites/knot.png')
sprites.lock = love.graphics.newImage('sprites/lock.png')
sprites.logo = love.graphics.newImage('sprites/logo.png')
sprites.scissors = love.graphics.newImage('sprites/scissors.png')
sprites.scissorsBottom = love.graphics.newImage('sprites/scissors_bottom.png')

sprites.playerVictory = love.graphics.newImage('sprites/player_victory.png')
sprites.playerHead = love.graphics.newImage('sprites/player_head.png')
sprites.playerHeadCut = love.graphics.newImage('sprites/player_head_cut.png')
sprites.playerMid = love.graphics.newImage('sprites/player_mid.png')
sprites.playerMidCut = love.graphics.newImage('sprites/player_mid_cut.png')
sprites.playerTail = love.graphics.newImage('sprites/player_tail.png')
sprites.playerTailCut = love.graphics.newImage('sprites/player_tail_cut.png')
sprites.playerCurve = love.graphics.newImage('sprites/player_curve.png')
sprites.playerCurveCut = love.graphics.newImage('sprites/player_curve_cut.png')
sprites.playerCurveAlt = love.graphics.newImage('sprites/player_curve_2.png')
sprites.playerCurveAltCut = love.graphics.newImage('sprites/player_curve_2_cut.png')
