return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.5",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 22,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 16,
  nextobjectid = 578,
  properties = {},
  tilesets = {
    {
      name = "[M]flower",
      firstgid = 1,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]flower.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Rocks2",
      firstgid = 37,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 24,
      image = "assets/[M]Rocks2.png",
      imagewidth = 768,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 384,
      tiles = {}
    },
    {
      name = "[M]Daisy",
      firstgid = 421,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 12,
      image = "assets/[M]Daisy.png",
      imagewidth = 384,
      imageheight = 384,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 144,
      tiles = {}
    },
    {
      name = "[M]Narcis",
      firstgid = 565,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]Narcis.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Grass",
      firstgid = 601,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 9,
      image = "assets/[M]Grass.png",
      imagewidth = 288,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 54,
      tiles = {}
    },
    {
      name = "[M]Various",
      firstgid = 655,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 10,
      image = "assets/[M]Various.png",
      imagewidth = 320,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 40,
      tiles = {}
    },
    {
      name = "[M]Forest",
      firstgid = 695,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 5,
      image = "assets/[M]Forest.png",
      imagewidth = 160,
      imageheight = 96,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 15,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "tiles",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "WQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAFsCAABbAgAAWwIAAA=="
    },
    {
      type = "tilelayer",
      id = 12,
      name = "tilesover",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaAgAAWgIAAFoCAABaAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAIAYFoCAABaAgAAggIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWgIAAFoCAABaAgAAWgIAAHYCAAB1AgAAeAIAAHwCAAB2AgAAdwIAAHgCAAB6AgAAdgIAAHcCAAB0AgAAewIAAGwCAABaAgAAWgIAAGsCAAB2AgAAeAIAAHwCAAAAAAAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAAAAAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAAB7AgAAdQIAAHgCAAB2AgAAZQIAAAAAAAAAAAAAAAAAAAAAAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAHgCAEB2AgBAeQIAQGMCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAGsCAAB8AgAAewIAAHsCAAB2AgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAAAAAAAAAAAAAAAAAAB4AgBgWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAAAAAAAAAAAAAAAAAewIAYFoCAABmAgAAiwIAAI0CAACMAgAAiwIAAIwCAACMAgAAiAIAAIkCAACIAgAAigIAAIgCAACMAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAAAAAAAAAAAAAAAAAHkCAGBaAgAAagIAgHcCAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAAAAAAAAAAAAAH0CAGBaAgAAWgIAAH8CAKB2AgCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAAAAAAAAAAAB9AgBgWgIAAFoCAAB9AgDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAAAAAAAAAAAAfQIAYFoCAABaAgAAggIA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAYgIAAHoCAMB6AgDAfAIAwHgCAMB3AgDAYwIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAAAAAAAAAAAAAIMCAGBaAgAAWgIAAIMCAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAGICAAB2AgDAdgIAwG4CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHcCAGBaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAAAAAAAAAAACFAgBgWgIAAFoCAACDAgDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAAB6AgCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABtAgAAdgIAwHUCAMBiAgCgWgIAAFoCAABaAgAAWgIAAAAAAAAAAAAAgAIAYFoCAABaAgAAhAIA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAegIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbQIAAHsCAMBjAgAAWgIAAFoCAAAAAAAAAAAAAIMCAGBaAgAAWgIAAIMCAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAGMCAMBkAgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAIAYFoCAABaAgAAAAAAAAAAAACFAgBgWgIAAFoCAABrAgAAdgIAAHYCAAB0AgAAdQIAAHQCAAB2AgAAAAAAAAAAAAAAAAAAAAAAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABiAgAAbQIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHkCAGBaAgAAWgIAAAAAAAAAAAAAhAIAYFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABiAgAAbgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQCAAB6AgAAdAIAAGUCAAAAAAAAAAAAAAAAAAB4AgBgWgIAAFoCAAAAAAAAAAAAAGoCAEBaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAawIAAHgCAAB7AgAAfAIAAHcCAAB7AgAAdAIAAHUCAABsAgAAWgIAAGICAABuAgAAAAAAAAAAAABkAgAAbAIAAFoCAABaAgAAAAAAAAAAAABwAgAAiAIAAIcCAACJAgAAjQIAAIgCAACLAgAAhgIAAIcCAACIAgAAiwIAAIwCAACNAgAAjgIAAIgCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABiAgBgfAIAAHoCAAB1AgAAawIAYFoCAABaAgAAWgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACOAgAAiwIAAI4CAACNAgAAhwIAAI4CAACHAgAAigIAAIsCAABpAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABoAgAAjAIAAI4CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAIAAIwCAACMAgAAjgIAAIoCAABnAgAAWgIAAFoCAABmAgAAcQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcwIAAFoCAABaAgAAagIAgAAAAAAAAAAAAAAAAA=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "elements",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAMQAAADIAAAAzAAAANAAAADUAAAA2AAAAAAAAAAAAAAAAAAAAAAAAAIkAAACKAAAAiwAAAIwAAACNAAAAjgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAA8QAAAPIAAADzAAAA9AAAAPUAAAD2AAAA9wAAAPgAAAD5AAAASAAAAEkAAABKAAAASwAAAEwAAABNAAAATgAAAAAAAAAAAAAAAAAAAAAAAAChAAAAogAAAKMAAACkAAAApQAAAKYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAEAAAkBAAAKAQAACwEAAAwBAAANAQAADgEAAA8BAAAQAQAAEQEAAGAAAABhAAAAYgAAAGMAAABkAAAAZQAAAGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACABAAAhAQAAIgEAACMBAAAkAQAAJQEAACYBAAAnAQAAKAEAACkBAAB4AAAAeQAAAHoAAAB7AAAAfAAAAH0AAAB+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AQAAOQEAADoBAAA7AQAAPAEAAD0BAAA+AQAAPwEAAEABAABBAQAAkAAAAJEAAACSAAAAkwAAAJQAAACVAAAAlgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAEAAFEBAABSAQAAUwEAAFQBAABVAQAAVgEAAFcBAABYAQAAWQEAAKgAAACpAAAAqgAAAKsAAACsAAAArQAAAK4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGgBAABpAQAAagEAAGsBAABsAQAAbQEAAG4BAABvAQAAcAEAAHEBAADAAAAAwQAAAMIAAADDAAAAxAAAAMUAAADGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAAgQEAAIIBAACDAQAAhAEAAIUBAACGAQAAhwEAAIgBAACJAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    },
    {
      type = "tilelayer",
      id = 15,
      name = "over",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "uwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAAMQCAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC/AgDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUCAAA2AgAANwIAADgCAAA5AgAAOgIAAAAAAAC7AgDAxAIAwLkCAADCAgDAuQIAAMICAMDCAgDAwQIAwLsCAAC7AgAAuwIAALcCAAC4AgAAuQIAALkCAAC6AgAAuwIAoLsCAAC7AgAAtwIAALgCAAC5AgAAvgIAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7AgAAPAIAAD0CAAA+AgAAPwIAAEACAAAAAAAAuwIAwL8CAMAAAAAAAAAAAAAAAAAAAAAAAAAAAL8CAAC7AgAAuwIAALsCAAC8AgAAAAAAAAAAAAAAAAAAvwIAALsCAKC3AgAAuAIAAL0CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQQIAAEICAABDAgAARAIAAEUCAABGAgAAAAAAALsCAMC/AgDAAAAAAAAAAAAAAAAAAAAAAAAAAAC+AgBgugIAALsCAAC7AgAAwQIAAL4CAKAAAAAAvQIAwLcCAMC7AgAAvAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcCAABIAgAASQIAAEoCAABLAgAATAIAAAAAAAC7AgDAvwIAwAAAAAAAAAAAAAAAAAAAAAAAAAAAvgIAALcCAMC7AgAAuwIAALcCAAC+AgDAAAAAAL4CAGC5AgAAugIAAMECAAC9AgBgAAAAAL4CAADDAgAAuAIAQL0CAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNAgAATgIAAE8CAABQAgAAUQIAAFICAAAAAAAAuwIAwLoCAMC9AgBgAAAAAAAAAAAAAAAAAAAAAL8CAAC7AgDAuwIAALsCAADBAgAAwQIAAL4CAKAAAAAAvQIAwMQCAAC7AgAAvAIAAAAAAAC/AgAAuwIAQLsCAEC8AgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUwIAAFQCAABVAgAAVgIAAFcCAABYAgAAAAAAALsCAMC7AgDAwQIAAL4CAKAAAAAAvQIAwMMCAADEAgAAuwIAwLsCAAC7AgAAuwIAALsCAADEAgCgwgIAALoCAKC7AgAAuwIAAMECAADDAgAAxAIAALsCAEC7AgBAtwIAQLgCAEC5AgBAuAIAQL0CAEAAAAAAAAAAAL4CAADCAgAAwwIAAL4CAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7AgAAuwIAALsCAADBAgAAwgIAALcCAMC7AgDAuwIAwLsCAMC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAguwIAQLsCAEC7AgBAuwIAQLsCAEC7AgBAuwIAQLsCAEC3AgBAvwIAIMMCAADEAgAAtwIAALoCAAC8AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAILsCACC7AgAgtwIAILwCACDBAgAguwIAILsCACC7AgAguwIAALsCAAC7AgAAuwIAAMICAKC/AgAAwQIAAMICAADCAgAAwwIAAMICAADDAgAAwgIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCACC7AgAguwIAILgCACAAAAAAvQIAgLwCACDBAgAguwIAILcCAAC4AgAAuAIAALgCAAC9AgAAvgIAQL8CAOC3AgCAuwIAgLsCAIC7AgCAuwIAgLsCAIC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAguwIAILcCACC9AgAgAAAAAAAAAAAAAAAAwgIAILsCACC5AgAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvQIAgLgCAIC5AgCAuAIAgLcCAIC7AgCAuwIAALsCAAC7AgAAuwIAALsCAAC3AgAAwgIAwMECAMC7AgDAuwIAwLsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAILsCACC4AgAgAAAAAAAAAAAAAAAAAAAAAL4CAEC8AgAgvQIAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8AgCAuwIAgLsCAAC7AgAAuwIAALcCAAC4AgAAvQIAAAAAAAC8AgDAuwIAwLsCAMC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCACC7AgAguQIAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvQIAgLgCAIC7AgAAuwIAoLsCAKC8AgAAAAAAAAAAAAAAAAAAvgIAYL8CAGDEAgBguwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAwMECAKC5AgAAvwIA4L4CAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuwIAAMECAKC3AgCgvAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwwIAYLsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAMDCAgCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALsCAADCAgCgvQIAoL4CAMAAAAAAAAAAAAAAAAC+AgAAvQIAYMICAGC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgDAwwIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7AgAAwwIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAvAIAwLcCAGDBAgBguwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAwMQCAKC/AgCgvgIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuwIAAMQCAKC/AgCgvgIAoAAAAAAAAAAAAAAAALwCAMC7AgBguwIAYLsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAMC7AgDAuwIAwL8CAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALsCAAC7AgAAuwIAALwCAAAAAAAAvQIAwLgCAMC3AgDAuwIAwLsCAMC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgDAuwIAwLsCAMC4AgBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7AgAAuwIAALsCAADBAgAAwgIAAMQCAAC7AgDAuwIAwLsCAMC7AgDAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAwLsCAMC7AgDAvAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAuwIAALsCAAC7AgAAtwIAAL0CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    },
    {
      type = "objectgroup",
      id = 13,
      name = "level",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["direction"] = "left",
        ["goal"] = 14,
        ["length"] = 6,
        ["x"] = 31,
        ["y"] = 16
      },
      objects = {}
    },
    {
      type = "objectgroup",
      id = 14,
      name = "water",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 224,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 238,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 243,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 247,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 394,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 397,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 398,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 402,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 403,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 404,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 405,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 406,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 408,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 409,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 410,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 411,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 412,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 413,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 415,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 418,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 419,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 421,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 422,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 423,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 424,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 425,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 426,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 427,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 428,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 429,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 430,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 431,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 432,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 433,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 434,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 435,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 462,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 463,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 464,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 465,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 466,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 467,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 468,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 469,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 470,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 471,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 472,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 473,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 475,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 476,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 477,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 479,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 480,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 481,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 482,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 483,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 484,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 485,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 486,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 487,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 488,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 489,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 490,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 491,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 492,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 493,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 494,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 495,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 496,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 3,
      name = "walls",
      visible = true,
      opacity = 0.97,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 436,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 437,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 438,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 439,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 440,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 441,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 442,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 443,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 444,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 445,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 446,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 447,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 448,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 449,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 450,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 452,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 453,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 454,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 455,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 456,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 457,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 458,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 459,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 460,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 461,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 498,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 499,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 506,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 507,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 508,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 509,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 510,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 511,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 512,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 513,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 514,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 515,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 516,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 517,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 518,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 519,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 520,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 521,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 522,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 523,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 524,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 526,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 527,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 528,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 529,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 530,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 531,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 532,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 533,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 534,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 535,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 536,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 537,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 538,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 539,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 540,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 541,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 542,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 543,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 544,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 545,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 546,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 547,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 548,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 549,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 550,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 551,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 552,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 2,
      name = "knots",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 387,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 389,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 390,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 7,
      name = "checkpoints",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "scissors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 9,
      name = "doors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["Number"] = 1
      },
      objects = {
        {
          id = 571,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Number"] = 1
          }
        },
        {
          id = 572,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Yellow",
            ["Number"] = 2
          }
        },
        {
          id = 573,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Blue",
            ["Number"] = 3
          }
        },
        {
          id = 574,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Green",
            ["Number"] = 4
          }
        },
        {
          id = 575,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "White",
            ["Number"] = 5
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "keys",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 553,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Door"] = 1
          }
        },
        {
          id = 554,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Door"] = 1
          }
        },
        {
          id = 555,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Yellow",
            ["Door"] = 2
          }
        },
        {
          id = 556,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Yellow",
            ["Door"] = 2
          }
        },
        {
          id = 557,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Yellow",
            ["Door"] = 2
          }
        },
        {
          id = 558,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Blue",
            ["Door"] = 3
          }
        },
        {
          id = 559,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Blue",
            ["Door"] = 3
          }
        },
        {
          id = 560,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Yellow",
            ["Door"] = 2
          }
        },
        {
          id = 561,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Green",
            ["Door"] = 4
          }
        },
        {
          id = 562,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Green",
            ["Door"] = 4
          }
        },
        {
          id = 563,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Green",
            ["Door"] = 4
          }
        },
        {
          id = 564,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "White",
            ["Door"] = 5
          }
        },
        {
          id = 565,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "White",
            ["Door"] = 5
          }
        },
        {
          id = 576,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Blue",
            ["Door"] = 3
          }
        },
        {
          id = 577,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Color"] = "Green",
            ["Door"] = 4
          }
        }
      }
    }
  }
}
