return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.5",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 22,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 16,
  nextobjectid = 387,
  properties = {},
  tilesets = {
    {
      name = "[M]flower",
      firstgid = 1,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]flower.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Rocks2",
      firstgid = 37,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 24,
      image = "assets/[M]Rocks2.png",
      imagewidth = 768,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 384,
      tiles = {}
    },
    {
      name = "[M]Daisy",
      firstgid = 421,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 12,
      image = "assets/[M]Daisy.png",
      imagewidth = 384,
      imageheight = 384,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 144,
      tiles = {}
    },
    {
      name = "[M]Narcis",
      firstgid = 565,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]Narcis.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Grass",
      firstgid = 601,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 9,
      image = "assets/[M]Grass.png",
      imagewidth = 288,
      imageheight = 224,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 63,
      tiles = {}
    },
    {
      name = "[M]Water",
      firstgid = 664,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]Water.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Various",
      firstgid = 700,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 10,
      image = "assets/[M]Various.png",
      imagewidth = 320,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 40,
      tiles = {}
    },
    {
      name = "[M]Forest",
      firstgid = 740,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 5,
      image = "assets/[M]Forest.png",
      imagewidth = 160,
      imageheight = 96,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 15,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "tiles",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "jQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAApQIAAKUCAAClAgAApQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAApQIAAKUCAAClAgAApQIAAKUCAAClAgAApQIAAKUCAAClAgAApQIAAKUCAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAKUCAAClAgAApgIAAKUCAAClAgAApQIAAKUCAAClAgAApQIAAKUCAAClAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAAClAgAApQIAAKUCAAClAgAApQIAAKUCAAClAgAApQIAAKUCAAClAgAApQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAI0CAACNAgAAjQIAAA=="
    },
    {
      type = "tilelayer",
      id = 12,
      name = "tilesover",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "aAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAHgCAACSAgAAkwIAAJQCAACVAgAAeQIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAHgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB5AgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAACMAgDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjAIAYGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAiwIA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIsCAGBoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAIoCAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKAgBgaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAACJAgDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiQIAYGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAngIAAJ8CAACgAgAAoQIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAgQIAAIkCAABgAgAAAAAAAF4CAACJAgAAigIAAIICAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAngIAAJ8CAACgAgAAnwIAAKACAACfAgAAoAIAAKQCAAAAAAAAAAAAALACAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAgQIAAIgCAACCAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAALMCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC2AgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAACBAgAAiAIAAIkCAACKAgAAiwIAAIwCAACJAgAAigIAAIsCAACMAgAAggIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAGgCAABoAgAAaAIAAA=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "elements",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    },
    {
      type = "tilelayer",
      id = 15,
      name = "over",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAPECAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADsAgDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADkAgAA5QIAAOYCAADmAgAA5wIAAOgCAKDoAgAA6AIAAOgCAADoAgAA5AIAAOUCAADmAgAA6wIAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6QIAAAAAAAAAAAAAAAAAAOwCAADoAgCg6AIAAOgCAADkAgAA5QIAAOoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAO4CAADrAgCgAAAAAOoCAMDkAgDA6AIAoOgCAADoAgAA6QIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOQCAADsAgBg6wIAwAAAAADrAgBg5gIAAOkCAKDnAgAA6AIAAO4CAADqAgBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6AIAAOgCAADoAgAA6AIAAOQCAADlAgAA5gIAAOUCAADqAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7AIAAOgCAADoAgAA6QIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOgCAADoAgAA6AIAAOgCAADpAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwCAADoAgAA6AIAAO4CAADvAgAA6wIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoAgAA6AIAAOQCAADlAgAA6gIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsAgAA6AIAAOgCAADoAgAA6AIAAOkCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6AIAoOgCAKDpAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7AIAAOgCAADoAgAA5AIAAOYCAADqAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO4CAKDkAgCg6QIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOwCAADoAgAA6AIAAOkCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvAgCg6gIAoOsCAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsAgAA6AIAAOgCAADuAgAA6wIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrAgAA8QIAAOgCAADoAgAA6AIAAOkCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPECAKDsAgCg6wIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7AIAAOgCAADoAgAA6AIAAOgCAADpAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoAgAA6AIAAOkCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrAgAA8AIAAPECAADoAgAA6AIAwO4CAKDkAgCg7gIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6AIAAOgCAADuAgAA7wIAAOsCAKAAAAAAAAAAAAAAAAAAAAAAAAAAAOsCAADvAgAA8QIAAOgCAADoAgAA6AIAAOgCAMDvAgCg6gIAoOsCAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOgCAADoAgAA6AIAAOgCAADxAgCg6gIAYAAAAAAAAAAAAAAAAAAAAADsAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgDA8AIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoAgAA6AIAAOgCAADoAgAA6AIAAO4CAADvAgAA6wIAoAAAAADqAgDA8QIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAwPECAKDsAgCg6wIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAPECAKDvAgAA5wIAoOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAMDoAgDA6AIAwOwCAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgDA6AIAwOgCAMDlAgBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAwOgCAMDoAgDA6QIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA6AIAAOgCAADoAgAA5AIAAOoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    },
    {
      type = "objectgroup",
      id = 13,
      name = "level",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["goal"] = 14,
        ["length"] = 6,
        ["x"] = 5,
        ["y"] = 6
      },
      objects = {}
    },
    {
      type = "objectgroup",
      id = 14,
      name = "water",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 224,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 238,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 243,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 288,
          width = 0,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 247,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 3,
      name = "walls",
      visible = true,
      opacity = 0.97,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 2,
      name = "knots",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 384,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 385,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 386,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 7,
      name = "checkpoints",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "scissors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 9,
      name = "doors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["Number"] = 1
      },
      objects = {}
    },
    {
      type = "objectgroup",
      id = 11,
      name = "keys",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    }
  }
}
