return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.5",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 22,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 17,
  nextobjectid = 229,
  properties = {},
  tilesets = {
    {
      name = "[M]Flowers",
      firstgid = 1,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]flower.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Rocks2",
      firstgid = 37,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 24,
      image = "assets/[M]Rocks2.png",
      imagewidth = 768,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 384,
      tiles = {}
    },
    {
      name = "[M]Daisy",
      firstgid = 421,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 12,
      image = "assets/[M]Daisy.png",
      imagewidth = 384,
      imageheight = 384,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 144,
      tiles = {}
    },
    {
      name = "[M]Narcis",
      firstgid = 565,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]Narcis.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Grass",
      firstgid = 601,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 9,
      image = "assets/[M]Grass.png",
      imagewidth = 288,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 54,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "tiles",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "WQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAFkCAABZAgAAWQIAAA=="
    },
    {
      type = "tilelayer",
      id = 12,
      name = "tilesover",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "WgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAdQIAoHYCAGBaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABiAgAAeQIAwG4CAABtAgAAeQIAwGMCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAegIAoAAAAAAAAAAAAAAAAAAAAAB5AgBgWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAYgIAAG4CAAAAAAAAAAAAAAAAAAAAAAAAewIAYFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAHYCAKAAAAAAAAAAAAAAAAAAAAAAAAAAAHwCAGBaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAYgIAAHgCAMB3AgDAdgIAwHUCAMBjAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAAB0AgCgAAAAAAAAAAAAAAAAAAAAAAAAAAB3AgBgWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAHYCAKAAAAAAAAAAAAAAAAAAAAAAdwIAYFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAdAIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAewIAYFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAAB3AgCgAAAAAAAAAAAAAAAAAAAAAHYCAGBaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAHQCAKAAAAAAAAAAAAAAAAAAAAAAAAAAAGQCAGBsAgBgWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAAB3AgDAdwIAwHYCAMB6AgDAfAIAwHkCAMB7AgDAbAIAYFoCAABiAgAAbgIAAAAAAAAAAAAAAAAAAAAAAABtAgAAYwIAAGICAAB2AgDAfAIAwHkCAMB3AgDAewIAwHwCAMBuAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbQIAAHgCAMB8AgDAdgIAwHoCAMB4AgDAeAIAwHgCAMB8AgDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG0CAAB0AgDAbgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG0CAABuAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkAgAAeAIAAGUCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQCAAB5AgAAYwIAoFoCAABrAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdQIAAHUCAAB2AgAAeAIAAHsCAAB2AgAAewIAAGUCAAAAAAAAAAAAAGQCAABjAgCgWgIAAFoCAABaAgAAWgIAAGICAGB2AgAAdgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkAgAAeQIAAG0CAMAAAAAAAAAAAAAAAAAAAAAAbgIAwHgCAAB2AgAAdwIAAGUCAAAAAAAAAAAAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABrAgAAdwIAAHYCAABsAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABrAgAAbQIAwAAAAAAAAAAAAAAAAAAAAAAAAAAAdwIAYFoCAABjAgDAAAAAAAAAAAAAAAAAZQIAYGICAMBaAgAAWgIAAFoCAABrAgAAeAIAAGQCAKBaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAGMCAMBkAgCgAAAAAAAAAAAAAAAAZQIAYGwCAABaAgAAWgIAAHgCAKAAAAAAAAAAAHQCAGBaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABiAgBgWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAdAIAoAAAAAAAAAAAZAIAAGsCAGBaAgAAWgIAAFoCAABjAgDAdAIAAHUCAABjAgCgWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAHUCAKAAAAAAAAAAAHcCAGBaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAAB2AgCgAAAAAAAAAAB2AgBgWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAYgIAYHYCAAB3AgAAbAIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAYgIAAGMCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAYgIAAG4CAAB3AgBgWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAFoCAABaAgAAWgIAAA=="
    },
    {
      type = "tilelayer",
      id = 16,
      name = "elements",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAPQAAAD1AAAA9gAAAPcAAAD4AAAA+QAAAPoAAAAAAAAAAAAAAAAAAAAIAQAACQEAAAoBAAALAQAADAEAAA0BAAAOAQAAQwAAAEQAAAARAQAAEgEAABMBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAADxAAAA8gAAAPMAAAD0AAAA9QAAAPYAAAD3AAAA+AAAAAAAAAAMAQAADQEAAA4BAAAPAQAAEAEAABEBAAASAQAAAAAAAAAAAAAAAAAAIAEAACEBAAAiAQAAIwEAACQBAAAlAQAAJgEAACcBAAAoAQAAKQEAACoBAAArAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAQAACQEAAAoBAAALAQAADAEAAA0BAAAOAQAADwEAABABAAAAAAAAJAEAACUBAAAmAQAAJwEAACgBAAApAQAAKgEAAAAAAAAAAAAAAAAAADgBAAA5AQAAOgEAADsBAAA8AQAAPQEAAD4BAAA/AQAAQAEAAEEBAABCAQAAQwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAEAACEBAAAiAQAAIwEAACQBAAAlAQAAJgEAACcBAAAoAQAAAAAAADwBAAA9AQAAPgEAAD8BAABAAQAAQQEAAEIBAAAAAAAAAAAAAAAAAABQAQAAUQEAAFIBAABTAQAAVAEAAFUBAABWAQAAVwEAAFgBAABZAQAAWgEAAFsBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgBAAA5AQAAOgEAADsBAAA8AQAAPQEAAD4BAAA/AQAAQAEAAAAAAABUAQAAVQEAAFYBAABXAQAAWAEAAFkBAABaAQAAAAAAAAAAAAC7AAAAaAEAAGkBAABqAQAAawEAAGwBAABtAQAAbgEAAG8BAABwAQAAcQEAAHIBAABzAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUQEAAFIBAABTAQAAVAEAAFUBAABWAQAAVwEAAFgBAABrAQAAbAEAAG0BAABuAQAAbwEAAHABAABxAQAAcgEAAAAAAAAAAAAAAAAAAIABAACBAQAAggEAAIMBAACEAQAAhQEAAIYBAACHAQAAiAEAAIkBAACKAQAAiwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAEAAGkBAABqAQAAawEAAGwBAABtAQAAbgEAAG8BAABwAQAAgwEAAIQBAACFAQAAhgEAAIcBAACIAQAAiQEAAIoBAAAAAAAAAAAAAAAAAACYAQAAmQEAAJoBAACbAQAAnAEAAJ0BAACeAQAAnwEAAKABAAChAQAAogEAAKMBAAAAAAAAAAAAAFMCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIABAACBAQAAggEAAIMBAACEAQAAhQEAAIYBAACHAQAAiAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQAAABoAAAAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAgAAAAIQAAACIAAAAAAAAAAAAAABkAAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfAAAAIAAAACEAAAAfAAAAIAAAACEAAAAiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlAAAAJUAAACWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArwEAALABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAMQAAADIAAAAzAAAANAAAADUAAAA2AAAANwAAADgAAAA5AAAAOgAAAAAAAAAAAAAAAAAAADAAAAAxAAAAMgAAADMAAAA0AAAANQAAADYAAAAbAQAAHAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAEkAAABKAAAASwAAAEwAAABNAAAATgAAAE8AAABQAAAAUQAAAFIAAAAAAAAAAAAAAAAAAABIAAAASQAAAEoAAABLAAAATAAAAE0AAABOAAAAMwEAADQBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAABhAAAAYgAAAGMAAABkAAAAZQAAAGYAAABnAAAAaAAAAGkAAABqAAAAAAAAAAAAAAAAAAAAYAAAAGEAAABiAAAAYwAAAGQAAABlAAAAZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAeQAAAHoAAAB7AAAAfAAAAH0AAAB+AAAAfwAAAIAAAACBAAAAggAAAAAAAAAAAAAAAAAAAHgAAAB5AAAAegAAAHsAAAB8AAAAfQAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAJEAAACSAAAAkwAAAJQAAACVAAAAlgAAAJcAAACYAAAAmQAAAJoAAAAAAAAAAAAAAAAAAACQAAAAkQAAAJIAAACTAAAAlAAAAJUAAACWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKgAAACpAAAAqgAAAKsAAAAAAAAArQAAAK4AAACvAAAAsAAAALEAAACyAAAAAAAAAAAAAAAAAAAAqAAAAKkAAACqAAAAqwAAAKwAAACtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgIAAAAAAADAAAAAwQAAAAAAAAAAAAAAAAAAAMUAAADGAAAAxwAAAMgAAADJAAAAygAAAAAAAAAAAAAAAAAAAMAAAADBAAAAwgAAAMMAAADEAAAAxQAAAAAAAAAAAAAAAAAAAA=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "over",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcCAABIAgAASQIAAEoCAABLAgAATAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNAgAATgIAAE8CAABQAgAAUQIAAFICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUwIAAFQCAABVAgAAVgIAAFcCAABYAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFMCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQAAABoAAAAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAgAAAAIQAAACIAAAAAAAAAAAAAABkAAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArwEAALABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKgBAACpAQAAqgEAAKsBAACsAQAArQEAAK4BAACvAQAAsAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0AQAAtQEAALYBAAC3AQAAuAEAALkBAAC6AQAAuwEAALwBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQAAABlAAAAZgAAAAAAAAAAAAAAwAEAAMEBAADCAQAAwwEAAMQBAADFAQAAxgEAAMcBAADIAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAfQAAAH4AAAAAAAAAAAAAAMwBAADNAQAAzgEAAM8BAADQAQAA0QEAANIBAADTAQAA1AEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlAAAAJUAAACWAAAAAAAAAAAAAADYAQAA2QEAANoBAADbAQAA3AEAAN0BAADeAQAA3wEAAOABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC1AAAAtgAAALcAAAC4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKwAAACtAAAANQIAADYCAAA3AgAA5AEAAOUBAADmAQAA5wEAAOgBAADpAQAA6gEAAOsBAADsAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgIAAAAAAAAAAAAAzQAAAM4AAADPAAAA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEAAAAxQAAADsCAAA8AgAAPQIAAA=="
    },
    {
      type = "objectgroup",
      id = 13,
      name = "level",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["direction"] = "right",
        ["goal"] = 16,
        ["length"] = 4,
        ["x"] = 7,
        ["y"] = 10
      },
      objects = {}
    },
    {
      type = "objectgroup",
      id = 3,
      name = "walls",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 608,
          width = 32,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 214,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 215,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 217,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 220,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 223,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 225,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 226,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "",
          type = "",
          shape = "rectangle",
          x = 672,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 2,
      name = "knots",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 221,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 7,
      name = "checkpoints",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "scissors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 9,
      name = "doors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 11,
      name = "keys",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    }
  }
}
