return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.5",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 22,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 14,
  nextobjectid = 219,
  properties = {},
  tilesets = {
    {
      name = "[M]Various",
      firstgid = 1,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 10,
      image = "assets/various.png",
      imagewidth = 320,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 40,
      tiles = {}
    },
    {
      name = "[M]flower",
      firstgid = 41,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]flower.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Rocks2",
      firstgid = 77,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 24,
      image = "assets/[M]Rocks2.png",
      imagewidth = 768,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 384,
      tiles = {}
    },
    {
      name = "[M]Daisy",
      firstgid = 461,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 12,
      image = "assets/[M]Daisy.png",
      imagewidth = 384,
      imageheight = 384,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 144,
      tiles = {}
    },
    {
      name = "[M]Narcis",
      firstgid = 605,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]Narcis.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Grass",
      firstgid = 641,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 9,
      image = "assets/[M]Grass.png",
      imagewidth = 288,
      imageheight = 224,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 63,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "tiles",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "tQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAAA=="
    },
    {
      type = "tilelayer",
      id = 12,
      name = "tilesover",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGAgAAsQIAALICAACzAgAAtAIAAIcCAACIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIYCAACxAgAAsgIAALMCAACxAgAAsgIAALMCAAC0AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjwIAAJACAACQAgAAkAIAAJACAACQAgAAqQIAAIgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACPAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAKkCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI8CAACQAgAApAIAAJACAACQAgAArQIAAJACAACRAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACxAgAAqgIAAJACAACQAgAAkAIAAJACAACQAgAApAIAAJACAACQAgAAsAIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIYCAACqAgAAkAIAAJACAACQAgAAkgIAAJACAACQAgAAsAIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALECAACqAgAAkAIAAJACAACQAgAAkAIAAJICAACQAgAAkAIAAJACAACQAgAAtgIAALECAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAgAgkAIAAJICAACQAgAAkAIAAJACAACQAgAAkAIAALECAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsQIAAKoCAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACyAgCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsQIAIJACAACQAgAAkAIAAJICAACQAgAAkAIAAJsCAACyAgCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGAgAAqgIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAK0CAACQAgAAkAIAAJACAACbAgAAkAIAAJACAACQAgAAqQIAAIgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAALICACCQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAsAIAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjwIAAJACAACQAgAAkAIAAK0CAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACbAgAAkAIAAJACAACRAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoQIAAJACAACQAgAAkAIAAJsCAACQAgAAkAIAALECAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAChAgAAkAIAAJACAACbAgAAkAIAAJACAACQAgAAkAIAAJICAACQAgAAkAIAAJACAACQAgAAkAIAAKQCAACQAgAAkQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKoCAACQAgAAkAIAAJACAACQAgAArQIAAJACAACyAgCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGAgAAqgIAAJACAACQAgAAkAIAAJACAACQAgAArQIAAJACAACQAgAAkAIAAJsCAACQAgAAkAIAAJACAACQAgAAoAIAAJoCAAAAAAAAAAAAAAAAAAAAAAAAhgIAAKoCAACQAgAAkAIAAJACAACQAgAAkAIAAJICAACQAgAAqQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjwIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAKACAAC6AgAAuwIAAJoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAALACACCQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACpAgAAAAAAAAAAAAAAAAAAhgIAALECAACyAgAAswIAAKoCAACQAgAAkAIAAJACAACQAgAAkAIAAJICAACQAgAAkAIAAJACAACQAgAAkAIAAKACAACaAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACxAgAgkAIAAK0CAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAKkCAACwAgAAsQIAAKoCAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACbAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAKACAACaAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsgIAIJACAACQAgAAkAIAAJICAACQAgAAkAIAAJACAACbAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJICAACQAgAAkAIAAJACAACRAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAChAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkQIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjwIAAJACAACkAgAAkAIAAJACAACkAgAAkAIAAJACAACQAgAAkgIAAJACAACQAgAAmwIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJICAACQAgAAkAIAAJsCAACQAgAAkAIAAJACAACQAgAAoAIAAJoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJgCAAChAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAoAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKECAACQAgAAkAIAAJICAACQAgAAkAIAAJACAACQAgAAmwIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACgAgAAmQIAAJoCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYAgAAugIAALsCAAC8AgAAoQIAALYCAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAoAIAAKECAACQAgAAkAIAAJACAAC2AgAAkAIAAKACAACZAgAAmgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJgCAAC5AgAAugIAALsCAAC8AgAAvQIAALsCAAC8AgAAvQIAAAAAAACYAgAAuQIAALoCAAC7AgAAvAIAAL0CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "elements",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYAAAAWQAAAFoAAABbAAAAXAAAAF0AAABeAAAAsQAAALIAAACzAAAAtAAAALUAAAC2AAAAsQAAALIAAACzAAAAtAAAALUAAAC2AAAAAAAAAAAAAAAAAAAAXwAAAGAAAABhAAAAYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAHEAAAByAAAAcwAAAHQAAAB1AAAAdgAAAMkAAADKAAAAywAAAMwAAADNAAAAzgAAAMkAAADKAAAAywAAAMwAAADNAAAAzgAAAAAAAAAAAAAAAAAAAHcAAAB4AAAAeQAAAHoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIgAAACJAAAAigAAAIsAAACMAAAAjQAAAI4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACPAAAAkAAAAJEAAACSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAoQAAAKIAAACjAAAApAAAAKUAAACmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApwAAAKgAAACpAAAAqgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuAAAALkAAAC6AAAAuwAAALwAAAC9AAAAvgAAAAAAAABTAAAAVAAAALEAAACyAAAAswAAALQAAAC1AAAAtgAAAH0AAAB+AAAAfwAAAIAAAAAAAAAAAAAAAL8AAADAAAAAwQAAAMIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAADRAAAA0gAAANMAAADUAAAA1QAAANYAAAAAAAAAawAAAGwAAADJAAAAygAAAMsAAADMAAAAzQAAAM4AAACVAAAAlgAAAJcAAACYAAAAAAAAAAAAAADXAAAA2AAAANkAAADaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADoAAAA6QAAAOoAAADrAAAA7AAAAO0AAADuAAAATQAAAE4AAABPAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7wAAAPAAAADxAAAA8gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAAFkAAABaAAAAAAAAAAAAAAAAAQAAAQEAAGUAAABmAAAAZwAAAGgAAAAGAQAABwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABxAAAAcgAAAAAAAAAAAAAAGAEAABkBAAAaAQAAAAAAAAAAAADrAAAAHgEAAB8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIAAAAiQAAAIoAAAAAAAAAAAAAADABAAAxAQAAMgEAADMBAAA0AQAANQEAADYBAAA3AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAKEAAACiAAAAAAAAAAAAAABIAQAASQEAAEoBAABLAQAATAEAAE0BAABOAQAATwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgAAAC5AAAAugAAALsAAAAAAAAAYAEAAGEBAABiAQAAYwEAAGQBAABlAQAAZgEAAGcBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQAAAA0QAAANIAAADTAAAAAAAAAHgBAAB5AQAAegEAAHsBAAB8AQAAfQEAAH4BAAB/AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6AAAAOkAAADqAAAAAAAAAAAAAACQAQAAkQEAAJIBAACTAQAAlAEAAJUBAACWAQAAlwEAAK8AAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAEAAKkBAACqAQAAqwEAAKwBAACtAQAArgEAAK8BAADHAAAAyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMABAADBAQAAwgEAAMMBAADEAQAAxQEAAMYBAADHAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    },
    {
      type = "objectgroup",
      id = 13,
      name = "level",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["goal"] = 14,
        ["length"] = 4,
        ["x"] = 8,
        ["y"] = 20
      },
      objects = {}
    },
    {
      type = "objectgroup",
      id = 3,
      name = "walls",
      visible = true,
      opacity = 0.97,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 2,
      name = "knots",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 7,
      name = "checkpoints",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "scissors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 448,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 9,
      name = "doors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["Number"] = 1
      },
      objects = {
        {
          id = 176,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Number"] = 1
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "keys",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Door"] = 1
          }
        },
        {
          id = 208,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1184,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Door"] = 1
          }
        }
      }
    }
  }
}
