return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.5",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 22,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 15,
  nextobjectid = 338,
  properties = {},
  tilesets = {
    {
      name = "[M]Various",
      firstgid = 1,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 10,
      image = "assets/various.png",
      imagewidth = 320,
      imageheight = 128,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 40,
      tiles = {}
    },
    {
      name = "[M]flower",
      firstgid = 41,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]flower.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Rocks2",
      firstgid = 77,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 24,
      image = "assets/[M]Rocks2.png",
      imagewidth = 768,
      imageheight = 512,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 384,
      tiles = {}
    },
    {
      name = "[M]Daisy",
      firstgid = 461,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 12,
      image = "assets/[M]Daisy.png",
      imagewidth = 384,
      imageheight = 384,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 144,
      tiles = {}
    },
    {
      name = "[M]Narcis",
      firstgid = 605,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]Narcis.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    },
    {
      name = "[M]Grass",
      firstgid = 641,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 9,
      image = "assets/[M]Grass.png",
      imagewidth = 288,
      imageheight = 224,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 63,
      tiles = {}
    },
    {
      name = "[M]Water",
      firstgid = 704,
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      columns = 6,
      image = "assets/[M]Water.png",
      imagewidth = 192,
      imageheight = 192,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 32,
        height = 32
      },
      properties = {},
      terrains = {},
      tilecount = 36,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      id = 1,
      name = "tiles",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "tQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAA3QIAAN0CAADdAgAA3QIAAN0CAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAAN0CAADdAgAAygIAAMsCAADdAgAA3QIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAADdAgAA3QIAANACAADRAgAA3QIAAN0CAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAAN0CAADdAgAA3QIAAN0CAADdAgAA3QIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAAN0CAADdAgAA3QIAAN0CAADdAgAA3QIAAN0CAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAA3QIAANwCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAAN0CAADdAgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAADdAgAA3QIAAN0CAADKAgAAywIAAN0CAADdAgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAA3QIAAN0CAADdAgAA0AIAANECAADdAgAA3QIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAADdAgAA3QIAAN0CAADdAgAA3QIAAN0CAADcAgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAADdAgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAA3QIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAA3QIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAAN0CAADdAgAA3QIAAN0CAADdAgAA3QIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAADdAgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAAN0CAADdAgAA3QIAAN0CAADdAgAA3QIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAADdAgAA3QIAAN0CAADdAgAA3QIAAN0CAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAADdAgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAA3QIAAN0CAADdAgAA3QIAAN0CAADdAgAA3QIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAALUCAAC1AgAAtQIAAA=="
    },
    {
      type = "tilelayer",
      id = 12,
      name = "tilesover",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "kAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAA4QIAAAAAAAAAAAAAAAAAAN4CAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAxgIAAMwCAAAAAAAAAAAAAAAAAADeAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAOECAAAAAAAAAAAAAAAAAAAAAAAA3gIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAADhAgAAAAAAAAAAAAAAAAAAAAAAAN4CAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAA4QIAAAAAAAAAAAAAAAAAAAAAAADYAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAKkCAACIAgAAAAAAAAAAAAAAAAAA3gIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAA4QIAAAAAAAAAAAAAAAAAAM8CAADJAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAKkCAADVAgAAAAAAAAAAAAAAAAAAzwIAAMkCAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAA2wIAAAAAAAAAAAAAAAAAAAAAAADeAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAxgIAAMwCAAAAAAAAAAAAAAAAAAAAAAAAzwIAAMkCAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAOECAAAAAAAAAAAAAAAAAAAAAAAAAAAAANICAACqAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAADhAgAAAAAAAAAAAAAAAAAAAAAAAAAAAADYAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAqQIAANUCAAAAAAAAAAAAAAAAAAAAAAAA3gIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAADbAgAAAAAAAAAAAAAAAAAAAAAAAM8CAADJAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAADGAgAAzAIAAAAAAAAAAAAAAAAAAAAAAACGAgAAqgIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAA4QIAAAAAAAAAAAAAAAAAAAAAAACGAgAAqgIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAANsCAAAAAAAAAAAAAAAAAAAAAAAA2AIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACpAgAA1QIAAAAAAAAAAAAAAAAAAM8CAADJAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAANsCAAAAAAAAAAAAAAAAAACGAgAAqgIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAADhAgAAAAAAAAAAAACGAgAAqgIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAADGAgAAzAIAAAAAAAAAAAAA2AIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAA4QIAAAAAAAAAAAAAAAAAAN4CAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAJACAACQAgAAkAIAAA=="
    },
    {
      type = "tilelayer",
      id = 6,
      name = "elements",
      x = 0,
      y = 0,
      width = 40,
      height = 22,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAEAAAAAAAAAAAAAsQAAALIAAACzAAAAtAAAALUAAAC2AAAAVQAAAFYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgBAAAZAQAAGgEAAMkAAADKAAAAywAAAMwAAADNAAAAzgAAAG0AAABuAAAAIQEAACIBAAAjAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAQAAMQEAADIBAAAzAQAANAEAADUBAAA0AQAANQEAADYBAAA3AQAAOAEAADkBAAA6AQAAOwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAEAAEkBAABKAQAASwEAAEwBAABNAQAATAEAAE0BAABOAQAATwEAAFABAABRAQAAUgEAAFMBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGABAABhAQAAYgEAAGMBAABkAQAAZQEAAGQBAABlAQAAZgEAAGcBAABoAQAAaQEAAGoBAABrAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AQAAeQEAAHoBAAB7AQAAfAEAAH0BAAB8AQAAfQEAAH4BAAB/AQAAgAEAAIEBAACCAQAAgwEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAEAAJEBAACSAQAAkwEAAJQBAAAAAAAAlAEAAJUBAACWAQAAlwEAAJgBAACZAQAAmgEAAJsBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAAFkAAABaAAAAWwAAAFwAAABdAAAAXgAAAF8AAABgAAAAYQAAAGIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKgBAACpAQAAqgEAAKsBAACsAQAAAAAAAKwBAACtAQAArgEAAK8BAACwAQAAsQEAALIBAACzAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAABxAAAAcgAAAHMAAAB0AAAAdQAAAHYAAAB3AAAAeAAAAHkAAAB6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAQAAwQEAAMIBAADDAQAAxAEAAMUBAADEAQAAxQEAAMYBAADHAQAAyAEAAMkBAADKAQAAywEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIAAAAiQAAAIoAAACLAAAAjAAAAI0AAACOAAAAjwAAAJAAAACRAAAAkgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAKEAAACiAAAAowAAAKQAAAClAAAApgAAAKcAAACoAAAAqQAAAKoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgAAAC5AAAAugAAALsAAAC8AAAAvQAAAL4AAAC/AAAAwAAAAMEAAADCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADQAAAA0QAAANIAAABRAAAAUgAAANUAAADWAAAAUwAAAFQAAADZAAAA2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6AAAAOkAAADqAAAAaQAAAGoAAADtAAAA+gAAAGsAAABsAAAA8QAAAPIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF0CAABeAgAAXwIAAGACAABhAgAAYgIAACkAAAAqAAAAKwAAACwAAAAtAAAALgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjAgAAZAIAAGUCAABmAgAAZwIAAGgCAAAvAAAAMAAAADEAAAAyAAAAMwAAADQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaQIAAGoCAABrAgAAbAIAAG0CAABuAgAANQAAADYAAAA3AAAAOAAAADkAAAA6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG8CAABwAgAAcQIAAHICAABzAgAAdAIAADsAAAA8AAAAPQAAAD4AAAA/AAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1AgAAdgIAAHcCAAB4AgAAeQIAAHoCAABBAAAAQgAAAEMAAABEAAAARQAAAEYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAewIAAHwCAAB9AgAAfgIAAH8CAACAAgAARwAAAEgAAABJAAAASgAAAEsAAABMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
    },
    {
      type = "objectgroup",
      id = 13,
      name = "level",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["goal"] = 14,
        ["length"] = 5,
        ["x"] = 7,
        ["y"] = 17
      },
      objects = {}
    },
    {
      type = "objectgroup",
      id = 14,
      name = "water",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 290,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 291,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 0,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 292,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 293,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 294,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 295,
          name = "",
          type = "",
          shape = "rectangle",
          x = 544,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 296,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 297,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 298,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 299,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 300,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 301,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 302,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 303,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 304,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 305,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 306,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 307,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 310,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 311,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 312,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 313,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 314,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 316,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 317,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 318,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 319,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 320,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 321,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 322,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 323,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 324,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 325,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 326,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 327,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 328,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 329,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 480,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 330,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 331,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 332,
          name = "",
          type = "",
          shape = "rectangle",
          x = 736,
          y = 576,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 333,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 334,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 640,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 335,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 672,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 336,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 3,
      name = "walls",
      visible = true,
      opacity = 0.97,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 219,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 220,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 221,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 223,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 225,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 238,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 240,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 243,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 247,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 384,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 251,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 252,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 253,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 254,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 255,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 256,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 268,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 269,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 271,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 272,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 273,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 274,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 277,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 284,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 286,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 287,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 288,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 2,
      name = "knots",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 992,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 544,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1056,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 289,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 7,
      name = "checkpoints",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 448,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "scissors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      id = 9,
      name = "doors",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {
        ["Number"] = 1
      },
      objects = {
        {
          id = 176,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Number"] = 1
          }
        },
        {
          id = 206,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 416,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Number"] = 2
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 11,
      name = "keys",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 178,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 608,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Door"] = 1
          }
        },
        {
          id = 179,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Door"] = 1
          }
        },
        {
          id = 207,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Door"] = 2
          }
        },
        {
          id = 208,
          name = "",
          type = "",
          shape = "rectangle",
          x = 928,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["Door"] = 2
          }
        }
      }
    }
  }
}
